# Generated by Django 6.0 on 2026-01-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kisan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('category', models.CharField(choices=[('crop', 'Crop Info'), ('fertilizer', 'Fertilizer'), ('weather', 'Weather'), ('disease', 'Disease'), ('irrigation', 'Irrigation'), ('other', 'Other')], default='other', max_length=20)),
            ],
        ),
    ]
